### ISSUE TITLE
I have a problem with the gui library using monogame.extended

### ISSUE THREAD

**Issue by esengine** [MarcStan/MonoGame.Framework.WpfInterop#10]
![image](https://user-images.githubusercontent.com/18465053/45542102-6ca6f200-b843-11e8-8225-b30559da53bc.png)

I am experiencing this problem when I use a different ui library. I don't know if this is the cause of it being empty.

I think we need to improve this because most ui libraries have their own control scheme.

**Comment by MarcStan** [comment]
I have never used touch in the WPF interop, but I assume it's the same issue as I had with mouse and keyboard.

For mouse and keyboard I created WpfMouse and WpfKeyboard. You'll likely have to create a new abstraction for the touch APIs as well.

The big problem is that monogame assumes there is only one window (and that constraint is quite hardcoded) which is why I ended up writting WpfMouse/Keyboard that support multiple hosts/windows.

I'm afraid you'll have a hard time getting existing Monogame UI libraries to work inside the WPF interop.

My primary usecase of the interop was to create editors (with very minimal "ingame" gui).

**Comment by esengine** [comment]
Monogame is for cross-platform, it is very common to support touch, except for windows, there will be touch on most platforms. I will consider how to help you solve this problem. In order to solve this problem, I have to cancel the original monitor of the ui library. Or just let this ui library be compatible with you.

**Comment by MarcStan** [comment]
I'm not saying touch is uncommon, I just never used it in the interop as it is a WPF desktop application (I now have Windows touch devices as well, but back then it was quite uncommon).

Have a look at the mouse and keyboard classes I wrote, with the interop you can not use Mouse and Keyboard but only WpfMouse and WpfKeyboard.

The same has to happen for touch which means existing UI libraries that hardcoded "Touch.GetTouchState()" won't work.

However some UI libraries (like NuclexUI) allow you to inject your own input receivers which you can then wrap with a bit of interop code for wpf <-> monogame integration.

Back when I wrote multiplatform games I usually wrapped the input handlers myself (and then injected a touch input handler for windowsphone, vs. keyboard/mouse handlers for windows. For the wpf interop I then injected another mouse/keyboard handler using the Wpf interop input classes).

Is the GUI library you are having trouble with opensource somewhere? I could take a quick glance on what the best way to fix it would be.

**Comment by esengine** [comment]
https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended.Gui

**Comment by MarcStan** [comment]
Their TouchListener class uses the Monogame "TouchPanel.GetState()" call which is the issue.

They abstracted it nicely but TouchListener is not injected into GuiSystem. If they injected it (like IGuiRenderer) then you could have swapped it out for a custom "WpfTouchInput" and it would work.

The way they built it, you will have to modify their code.

I never really used other GUI frameworks when doing the WPF integration (it was always mainly for editors to build my games and then the games use GUI while running as "proper monogame").

**Comment by esengine** [comment]
You are right, I need to go to their side and submit a pr to modify these things. However, most ui libraries will not take into account that their control will be taken over by another library, which may be a flaw in their design.

**Comment by MarcStan** [comment]
Yes I have generally found this to be a problem. As I mentioned, most Monogame games/libraries assume that there is one window and the static input handlers: Mouse, Keyboard and Touch are available (an overall design flaw in the original XNA).

That's why I always ended up with my own UI wrappers and most of the time only used WPF interop for level editors, etc. where I don't need any UI libraries. With editors most UI controls where the WPF controls outside the game and then the monogame host only shows a few texts drawn via SpriteBatch along with the level.

The real game then obviously won't run in the editor, but I just launched that from a normal Monogame project where all UI libraries worked.

**Comment by esengine** [comment]
I support you to do this. I will help to improve this library when I am free. This library still has a lot of room for improvement. I am just developing the editor. I need this very much. If there is any problem, I will give you the first time.

**Comment by MarcStan** [comment]
Closing this as it is an issue with most GUI libraries and nothing that is fixable from my end.
