### ISSUE TITLE
I have encountered an error

### ISSUE THREAD

**Issue by esengine** [MarcStan/MonoGame.Framework.WpfInterop#15]
![qq 20190113135534](https://user-images.githubusercontent.com/18465053/51082094-39b23380-173b-11e9-93bb-a4e0440a12f2.png)

**Comment by MarcStan** [comment]
Can you provide a sample that reproduces the crash? And also give a bit more detail.

I assume you are using rendertargets in some way..

**Comment by esengine** [comment]
I don't know where to start posting code. So I will explain the error in detail here.

![qq 20190113200842](https://user-images.githubusercontent.com/18465053/51085056-07bac480-176f-11e9-9af5-446fb2b16b07.png)

first. i add an template.

```csharp
_resourceDictionary = new System.Windows.ResourceDictionary
			{
				Source = new Uri(
					"pack://application:,,,/CLEngine.Editor;component/Extensions/Scene/ResourceDictionary.xaml",
					UriKind.RelativeOrAbsolute)
			};
			EditorHelper.RegisterResources(_resourceDictionary);
```

`ResourceDictionary.xaml`

```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:scene="clr-namespace:CLEngine.Editor.Extensions.Scene">

    <DataTemplate DataType="{x:Type scene:SceneViewModel}">
        <scene:SceneView />
    </DataTemplate>

</ResourceDictionary>
```

`SceneView.xaml`


```xml
<UserControl x:Class="CLEngine.Editor.Extensions.Scene.SceneView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:scene="clr-namespace:CLEngine.Editor.Extensions.Scene"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
        <scene:GameScene></scene:GameScene>
    </Grid>
</UserControl>
```

`GameScene.cs`

```csharp
using Microsoft.Xna.Framework.Graphics;
using MonoGame.Framework.WpfInterop;

namespace CLEngine.Editor.Extensions.Scene
{
	public class GameScene : WpfGame
	{
		private IGraphicsDeviceService graphicsDeviceService;

		protected override void Initialize()
		{
			base.Initialize();
			
			graphicsDeviceService = new WpfGraphicsDeviceService(this);
		}
	}
}
```

This is all my core code, can you help me see why this is?

**Comment by MarcStan** [comment]
Initialize should look like this:

``` csharp
protected override void Initialize()
{
    graphicsDeviceService = new WpfGraphicsDeviceService(this);
    base.Initialize();
}
```

[As per the readme](https://github.com/MarcStan/MonoGame.Framework.WpfInterop/blob/master/MonoGame.Framework.WpfInterop/readme.txt) the **graphicsDeviceService must be created before calling base.Initialize()**.

Can you try this and confirm whether this prevents the crash?

**Comment by esengine** [comment]
Sorry, I posted the wrong code. I originally placed it there, but it still crashes. He has not yet implemented to initialize. Has crashed in the constructor

**Comment by esengine** [comment]
This is my stack

- ![1](https://user-images.githubusercontent.com/18465053/51085504-4f444f00-1775-11e9-8058-2ea2b2bbe201.png)

- ![2](https://user-images.githubusercontent.com/18465053/51085506-523f3f80-1775-11e9-9a31-0b49e76ffa87.png)

- ![3](https://user-images.githubusercontent.com/18465053/51085507-54090300-1775-11e9-95bd-5c88dc893152.png)

- ![4](https://user-images.githubusercontent.com/18465053/51085509-5703f380-1775-11e9-9223-18a6c7c77df0.png)

**Comment by MarcStan** [comment]
The code you shared isn't enough for me to reproduce (both UserControl and ResourceDictionaries work just fine for me).

Since you said "your project is very large":

I assume that your project used to work some time ago and some recent changes you made now cause the crash?

Can you try to undo the latest changes until you have a working version again? That way you will be able to narrow down which exact change introduced the crash.

**Comment by esengine** [comment]
https://github.com/DigitalRune/DigitalRune

Ok, I use the DigitalRune editor and use their editor to host your controls, so I don't know how to send their editor to you. Haha, I am worried that their project is too big for you to lose interest in my problem.

**Comment by MarcStan** [comment]
The size/number of dependencies is not a problem.

I'm just trying to understand what the root cause of the issue is.

If I understand DigitalRune then they already provide some form of editor.

How are you using my WpfInterop with it? And have you gotten WpfInterop to work with DigitalRune before?

**Comment by esengine** [comment]
I didn't use their core code, only the part of the WPF editor. They no longer maintain this project, so I want to learn about their projects. As I said above, I created a class that inherits WPF according to your rules and puts it into the userControl through their editor. This error occurred when I went to run. But I can't locate the problem with their WPF editor, or other problems.

**Comment by MarcStan** [comment]
Ah, ok I see.

So I am not too familiar with DigitalRune, but my understanding is that it already contains an editor/WPFInterop component itself ([as described here](https://github.com/DigitalRune/DigitalRune/wiki/DigitalRune-Editor)).

If you look at [their code here](https://github.com/DigitalRune/DigitalRune/tree/master/Source/DigitalRune.Graphics/Interop) you'll notice that it is very similar to mine (there used to be a very old WpfInterop sample from Microsoft that we all took as a base). So DigitalRune already contains all the interop code to run in WPF and you don't need my project.

If you want to play around with DigitalRune it is probably best to use their WpfInterop instead of mine.

My WpfInterop is also very basic and I also only tested it with the latest MonoGame version.

Meanwhile DigitalRune uses a [MonoGame fork](https://github.com/DigitalRune/MonoGame) that is quite modified and also outdated (151 commits by DigitalRune and 2000 commits behind the actual MonoGame). There is probably a whole lot of tiny changes between their MonoGame and the latest one.

Since their MonoGame is outdated by > 2 years it's probably best if you don't use my WpfInterop with their project but instead use their WpfInterop code directly.

**Comment by esengine** [comment]
Thank you for taking so much time to help me with this problem. I didn't use their Graphics library, so I chose to use your library, but it doesn't seem like a good way to be compatible with them. But still thank you very much for your patience to help me.
