### ISSUE TITLE
Frame Debugging with RenderDoc

### ISSUE THREAD

**Issue by DarkDestry** [MarcStan/MonoGame.Framework.WpfInterop#18]
Is it possible to use frame debuggers like RenderDoc or even the VS built in Graphics debugger? I haven't been able to see any frame activity on either tool and wonder if anyone is able to get it working.

**Comment by MarcStan** [comment]
Not sure, I haven't used either.

Perhaps its an issue with the interop between WPF (DirectX 9) and the Monogame rendering (DirectX 11). I don't think either of these tools support DirectX 9 directly.

Have you successfully used the debugging tools with a standard Monogame (DirectX based) project?

**Comment by DarkDestry** [comment]
I was able to run renderdoc with a standard monogame project. It correctly identifies it as DX11 API.

Running it with my WPF project, it was able to identify it as DX11. However it says that its `Not Presenting` and thus unable to capture a frame snapshot.

**Comment by trigger-segfault** [comment]
Do you have this issue with WPF apps in general? I'm wondering if it has something to do with the base of WPF that runs the DirectX presentation.

**Comment by DarkDestry** [comment]
I haven't tried with other WPF apps. Its the first time that I am using WPF with GPU operations.

**Comment by MarcStan** [comment]
> RenderDoc was able to identify it as DX11. However it says that its Not Presenting and thus unable to capture a frame snapshot.

I'm using a shared [DX9 device](https://github.com/MarcStan/MonoGame.Framework.WpfInterop/blob/master/MonoGame.Framework.WpfInterop/Internals/D3D9.cs) that Monogame/DX11 is able to draw into.

The actual rendering is then done by WPF/DX9 so RenderDoc saying "DX11 is not presenting" is probably the correct assertion since the actual presenting will be done by WPF via DX9, unfortunately I don't know enough about the internals to know exactly what's going on internally.

But I think getting another framedebugger to work with a basic WPF/DX9 app would be a good first step (the RenderDoc DX9 fork has not been updated since 2016 so not sure if it still works).
