### ISSUE TITLE
Can I upgrade monogame to 3.6?

### ISSUE THREAD

**Issue by esengine** [MarcStan/MonoGame.Framework.WpfInterop#6]
When I changed its version to 3.6, I couldn't find sharpdx9. I was confused because my editor was already due to monogame 3.6, I can't reference this library again with 3.6.

**Comment by MarcStan** [comment]
I think the problem is due to the SharpDX reference <HintPath> still pointing to 3.5.

Since Monogame doesn't use SharpDX Nuget but bundles it directly I have to reference the SharpDX versions from the Monogame nuget package. Pretty ugly stuff..

Since Monogame 3.6 has been out for ages, I just updated my nuget to use that version. So you can just update to 1.6.0.
